version: '3.8'

services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: ecommerce_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ecommerce_postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ecommerce_user"]
      interval: 30s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: ecommerce_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ecommerce_pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - ecommerce_network

volumes:
  ecommerce_postgres_data:
  ecommerce_pgadmin_data:

networks:
  ecommerce_network:
    driver: bridge